### ISSUE TITLE
MixCore isnt working on IIS 10.

### ISSUE THREAD

**Issue by GuruprasadMe** [mixcore/mix.core#284]
Hi Team,
Tried a ton of times, with different versions,
1. From https://github.com/mixcore/mix.core/tree/develop
2. From Project's default "Master" version", adding "mix.heart" separately.
3. From most recent version too.
4. Modified .Net 2.0, rolled back to 4.0 on IIS.
5. Made sure its a separate local domain
Still it doesn't proceed further while performing the initial Setup. Results with "Server Errors"
![mixcore_error1](https://user-images.githubusercontent.com/2157641/101790980-0b0c8580-3b29-11eb-9edb-b74186630355.png)

Nothing works, feeling tired as it doesn't work :'(
Please help!

**Comment by Smilefounder** [comment]
Hi @GuruprasadMe could you provide me with the domain to access and double check?
Or could you screenshot the bug from browser developer console?

**Comment by hldvuong** [comment]
I have same problem with you if you use database with Microsoft SQL Server

**I fixed by deploy the project using single local database file.**
After that, I open the local database file and export it's database to "source.sql"

Go Microsoft SQL Server Management Studio to connect Microsoft SQL Server,
then create new database
and import file source.sql

The end, I change database setting in file appsettings.json to SQL Server

That will run ok.

**Comment by GuruprasadMe** [comment]
> 
> 
> Hi @GuruprasadMe could you provide me with the domain to access and double check?
> Or could you screenshot the bug from browser developer console?

Dear @SmileFounder Im really upset, after struggling all the way from my local named domain (mix.local) from Dev machine to a realtime subdomain, I was able to get the setup page working along with the dashboard, but theres just a blank white page/content when I switch to the root url or any post that i create. The dashboard seemed interesting with options, but tired to see NO PAGES with any content. I cant share my public url on this public forum.
Thank you.

**Comment by Smilefounder** [comment]
Hi @GuruprasadMe so sorry for the issues. During the setup step, and at the last step. The screen shows up to ask you to choose the template and if you choosing the blank template. The site will be blank. There is an option that creates a simple blog site.

At the moment, our team still not setup the full default template properly yet. Kindly take a look at the samples here https://github.com/mixcore/mix.theme.clean-blog

The template is based on ASP.NET MVC standard.

I will close this issue at the moment, please feel free to open any other new issues.
